const mongoose = require("mongoose");

const ConsultationEchoPelvienneBaseSchema = new mongoose.Schema({
    titre_echo_pelvienne: { type: String, default: null },
    position_uterus: { type: String, default: null },
    lateralisation: { type: String, default: null },
    longueur: { type: Number },
    largeur: { type: Number },
    hauteur: { type: Number },
    longueur_totale: { type: Number },
    volume_uterin: { type: Number },
    volume_uterin_commentaire: { type: String, default: null },
    asymetrie: { type: String, default: null },
    paroi_anterieure: { type: Number },
    paroi_posterieure: { type: Number },
    mobilite: { type: String, default: null },
    structures: { type: String, default: null },
    commentaires_myometre: { type: String },
    cavite: { type: String, default: null },
    malformation: { type: String, default: null },
    largeur_interostiale: { type: Number },
    ligne_cavitaire: { type: String, default: null },
    hysterometrie: { type: Number },
    adenomyose: [{ type: String }],
    adenomyose_conclusion: [{ type: String }],
    type_dispositif_intra_uterin: { type: String, default: null },
    localisation_dispositif_intra_uterin: { type: String, default: null },
    anomalies_dispositif_intra_uterin: { type: String, default: null },
    dispositif_intra_tubaire: { type: Boolean },
    endometre_visualisation: { type: String, default: null },
    endometre_echogenicite: { type: String, default: null },
    endometre_epaisseur: { type: Number },
    col_longueur: { type: Number },
    col_aspect: { type: String, default: null },
    col_vascularisation: { type: String, default: null },
    commentaire_col_endometre: { type: String },
    ovaire_gauche_visibilite: { type: String, default: null },
    ovaire_gauche_aspect: { type: String, default: null },
    ovaire_gauche_longueur: { type: Number },
    ovaire_gauche_largeur: { type: Number },
    ovaire_gauche_hauteur: { type: Number },
    ovaire_gauche_volume: { type: Number },
    ovaire_gauche_mobilite: { type: String, default: null },
    ovaire_gauche_accessibilite: { type: String, default: null },
    ovaire_gauche_follicules: { type: String, default: null },
    ovaire_gauche_follicules_list: { type: String },
    ovaire_gauche_commentaire: { type: String },
    ovaire_droit_visibilite: { type: String, default: null },
    ovaire_droit_aspect: { type: String, default: null },
    ovaire_droit_longueur: { type: Number },
    ovaire_droit_largeur: { type: Number },
    ovaire_droit_hauteur: { type: Number },
    ovaire_droit_volume: { type: Number },
    ovaire_droit_mobilite: { type: String, default: null },
    ovaire_droit_accessibilite: { type: String, default: null },
    ovaire_droit_follicules: { type: String, default: null },
    ovaire_droit_follicules_list: { type: String },
    ovaire_droit_commentaire: { type: String },
    cul_de_sac_latero: { type: String, default: null },
    conclusion_echo: { type: String }
}, { timestamps: true });

module.exports = mongoose.model('ConsultationEchoPelvienneBase', ConsultationEchoPelvienneBaseSchema);
