const mongoose = require(mongoose);

const DonneesFoetusSchema = new mongoose.Schema({
  consultation: { type: String , maxlength:128, required: true },
  presentation: { type: String , maxlength:128 },
  Activite_cardiaque: { type: Number },
  mobilité: { type: String , maxlength:128 },
  poids: { type: Number },
  lcc: { type: Number },
  dat: { type: Number },
  cn: { type: Number },
  fc: { type: Number },
  bip: { type: Number },
  pc: { type: Number },
  pa: { type: Number },
  fumeur: { type: Number },
  bssinet_droit : { type: Number },
  bssinet_gauche : { type: Number },
  cc: { type: Number },
  cervelet: { type: Number },
  cubitus: { type: Number },
  dio: { type: Number },
  epn: { type: Number },
  humérus: { type: Number },
  opn: { type: Number },
  opn_presence: { type: Boolean },
  oreille: { type: Number },
  péroné: { type: Number },
  pied: { type: Number },
  placenta: { type: Number },
  radius: { type: Number },
  rein_droite: { type: Number },
  rein_gauche: { type: Number },
  thyroïde: { type: Number },
  tibia: { type: Number },
  vl: { type: Number },
  poids_estime: { type: Number },
  doppler_cordon_ip: { type: Number },
  doppler_cordon_ir: { type: Number },
  doppler_cordon_diastole: { type: Number },
  doppler_acm_ip: { type: Number },
  doppler_acm_ir: { type: Number },
  doppler_acm_vitesse: { type: Number },
  doppler_acm_mom: { type: Number },
  doppler_dv_ip: { type: Number },
  doppler_dv_ir: { type: Number },
  doppler_dv_onde: { type: Number },
  morpho_crane: { type: String , maxlength:128 },
  morpho_struct: { type: String , maxlength:128 },
  morpho_face: { type: String , maxlength:128 },
  morpho_thorax: { type: String , maxlength:128 },
  morpho_coeur: { type: String , maxlength:128 },
  morpho_pole_cepha: { type: String , maxlength:128 },
  morpho_abdo: { type: String , maxlength:128 },
  morpho_digest: { type: String , maxlength:128 },
  morpho_urine: { type: String , maxlength:128 },
  morpho_rachis: { type: String , maxlength:128 },
  morpho_membres: { type: String , maxlength:128 },
  morpho_oge: { type: String , maxlength:128 },
  mnnexe_liquide_amnio: { type: String , maxlength:128 },
  morpho_liquide_amnio: { type: String , maxlength:128 },
  morpho_trophoblaste_localisation: { type: String , maxlength:128 },
  morpho_trophoblaste_aspect: { type: String , maxlength:128 },
  morpho_decol: { type: String , maxlength:128 },
  morpho_placenta: { type: String , maxlength:128 },
  morpho_cordon: { type: String , maxlength:128 },
  morpho_cou: { type: String , maxlength:128 },
  commentaires: { type: String , maxlength:128 },
});

const DonneesFoetus = mongoose.model('DonneesFoetus', DonneesFoetusSchema);

module.exports = DonneesFoetus;