const express = require("express");

const AbsenceMedecinRoute = require("./routes/absencemedecin");
const AdmissionRoute = require("./routes/admission");
const AdresseRoute = require("./routes/adresse");
const AnalysesBiologiquesRoute = require("./routes/analysebiologique");
const AntecedentsRoute = require("./routes/antecedents");
const AntecedentsObstetriquesRoute =  require("./routes/antecedentsobstetriques");
const BordoreauRoute =  require("./routes/bordoreau");
const CategorieAntecedentsRoute = require("./routes/categorie_antecedent");
const CategorieConsultationRoute = require("./routes/categorie_consultation");
const CertificatRoute = require("./routes/certificats");
const ClotureCaisseRoute = require("./routes/cloture_caisse");
const CollectionAnalysesBiologiquesRoute = require("./routes/collectionanalysebiologique");
const CompteRoute  = require("./routes/compte");
const ConsultationRoute = require("./routes/consultation");
const ConsultationEchoCroissanceRoute = require("./routes/consultationechocroissance");
const ConsultationEchoPelvienneRoute = require("./routes/consultationechopelvienne");
const ConsultationGynecologiquesRoute = require("./routes/consultationgynecologique");
const DevicesRoute = require("./routes/devices");
const DonneesFoetusRoute=require("./routes/donnesfoetus");
const DossierFichierPatientRoute =require("./routes/dossier_fiche_patient");
const Echo11SARoute = require("./routes/echo11sa");
const EchoT1Route =require("./routes/echot1");
const EchoT2Route =require("./routes/echot2");
const EchoT3Route =require("./routes/echot3");
const EtablissementRoute =require("./routes/etablissement");
const FacturePatient =require("./routes/facture");
const FichierPatientRoute =require("./routes/fichier_patient");
const FormuleConsultationRoute =require("./routes/formuleconsultation");
const grossesseRoute = require("./routes/grossesse");
const ImageConsultationRoute =require("./routes/imageconsultation");
const InformationsConjointRoute =require("./routes/informationconjoint");
const InterrogatoirePMARoute =require("./routes/interrogatoirepma");
const LigneReglementsRoute =require("./routes/lignereglement");
const MesuresPatientRoute =require("./routes/mesurespatients");
const MotifAbsenceRoute =require("./routes/motifabsence");
const MotifConsultationRoute =require("./routes/motifconsultation");
const MotifRDVRoute =require("./routes/motifrdv");
const MyomeRoute =require("./routes/myome");
const OrdonnancesRoute =require("./routes/ordonnances");
const ParametrecompteRoute =require("./routes/parametrecompte");
const PatientRoute=require("./routes/patient");
const PhracierRoute=require("./routes/phraciers");
const PrescriptionRoute =require("./routes/prescription");
const PrescriptionanalysebiologiqueRoute =require("./routes/prescriptionanalysebiologique");
const ProfileRoute=require("./routes/profile");
const ProgrammeoperatoireRoute=require("./routes/programmeoperatoire");
const RdvRoute =require("./routes/rdv");
const ReglementsRoute =require("./routes/reglements");
const ResultatanalysebioRoute = require("./routes/resultatanalysebiologique");
const SouscategoriRoute = require("./routes/souscategorie");
const SrconsultationRoute = require("./routes/srconsultation");
const SuivitraitementpmaRoute = require("./routes/suivitraitementpma");
const TemplateeditionRoute = require("./routes/templateedition");
const TemplatePMARoute = require("./routes/templatePMA");
const TraitementRoute = require("./routes/traitements");
const TraitementvaleurpmaRoute = require("./routes/traitementvaleurpma");
const TypeordonannceRoute = require("./routes/typeordonnances");
const WorklistRoute = require("./routes/worklistitem");
 
const port = 5000;
const server = express();


server.use("/patient", PatientRoute);
server.use("/user/parametres/absence-medecin", AbsenceMedecinRoute);
server.use("/AdmissionRoute", AdmissionRoute);
server.use("/AdresseRoute", AdmissionRoute);
server.use("/AnalysesBiologiquesRoute", AnalysesBiologiquesRoute);
server.use("/AntecedentsRoute", AntecedentsRoute);
server.use("/AntecedentsObstetriquesRoute", AntecedentsObstetriquesRoute);
server.use("/BordoreauRoute", BordoreauRoute);
server.use("/CategorieAntecedentsRoute", CategorieAntecedentsRoute);
server.use("/CategorieConsultationRoute", CategorieConsultationRoute);
server.use("/CertificatRoute", CertificatRoute);
server.use("/ClotureCaisseRoute", ClotureCaisseRoute);
server.use("/CollectionAnalysesBiologiquesRoute", CollectionAnalysesBiologiquesRoute);
server.use("/CompteRoute", CompteRoute);
server.use("/ConsultationRoute", ConsultationRoute);
server.use("/ConsultationEchoCroissanceRoute", ConsultationEchoCroissanceRoute);
server.use("/ConsultationEchoPelvienneRoute", ConsultationEchoPelvienneRoute);
server.use("/ConsultationGynecologiquesRoute", ConsultationGynecologiquesRoute);
server.use("/DevicesRoute", DevicesRoute);
server.use("/DonneesFoetusRoute", DonneesFoetusRoute);
server.use("/DossierFichierPatientRoute", DossierFichierPatientRoute);
server.use("/Echo11SARoute", Echo11SARoute);
server.use("/EchoT1Route", EchoT1Route);
server.use("/EchoT2Route", EchoT2Route);
server.use("/EchoT3Route", EchoT3Route);
server.use("/EtablissementRoute", EtablissementRoute);
server.use("/FacturePatient", FacturePatient);
server.use("/FichierPatientRoute", FichierPatientRoute);
server.use("/FormuleConsultationRoute", FormuleConsultationRoute);
server.use("/grossesseRoute", grossesseRoute);
server.use("/ImageConsultationRoute", ImageConsultationRoute);
server.use("/InformationsConjointRoute", InformationsConjointRoute);
server.use("/InterrogatoirePMARoute", InterrogatoirePMARoute);
server.use("/LigneReglementsRoute", LigneReglementsRoute);
server.use("/MesuresPatientRoute", MesuresPatientRoute);
server.use("/MotifAbsenceRoute", MotifAbsenceRoute);
server.use("/MotifConsultationRoute", MotifConsultationRoute);
server.use("/MotifRDVRoute", MotifRDVRoute);
server.use("/MyomeRoute", MyomeRoute);
server.use("/OrdonnancesRoute", OrdonnancesRoute);
server.use("/ParametrecompteRoute", ParametrecompteRoute);
server.use("/PhracierRoute", PhracierRoute);
server.use("/PrescriptionRoute", PrescriptionRoute);
server.use("/PrescriptionanalysebiologiqueRoute", PrescriptionanalysebiologiqueRoute);
server.use("/ProfileRoute", ProfileRoute);
server.use("/ProgrammeoperatoireRoute", ProgrammeoperatoireRoute);
server.use("/RdvRoute", RdvRoute);
server.use("/ReglementsRoute", ReglementsRoute);
server.use("/ResultatanalysebioRoute", ResultatanalysebioRoute);
server.use("/SouscategoriRoute", SouscategoriRoute);
server.use("/SrconsultationRoute", SrconsultationRoute);
server.use("/SuivitraitementpmaRoute", SuivitraitementpmaRoute);
server.use("/TemplateeditionRoute", TemplateeditionRoute);
server.use("/TemplatePMARoute", TemplatePMARoute);
server.use("/TraitementRoute", TraitementRoute);
server.use("/TraitementvaleurpmaRoute", TraitementvaleurpmaRoute);
server.use("/TypeordonannceRoute", TypeordonannceRoute);
server.use("/WorklistRoute", WorklistRoute);



server.listen(port, () => console.log(`Server is running on port ${port}`));
